# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target '@Stake' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for @Stake

	pod 'ReachabilitySwift'

  target '@StakeTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target '@StakeUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end

target '@Stake Prod' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for @Stake Prod

end

target '@StakeDev' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for @StakeDev

end
